import { getTranscriptMeta } from '../../../services/captions-service'
import { videoTranscripts } from '../../../db/schema'
import { eq } from 'drizzle-orm'
import { useDb } from '../../../utils/db'

export default defineEventHandler(async (event) => {
  const videoId = getRouterParam(event, 'id')!
  const db = useDb()

  const row = await db.query.videoTranscripts.findFirst({
    where: eq(videoTranscripts.videoId, videoId),
  })

  if (!row) return { transcript: null, meta: null }

  return {
    transcript: row.transcript,
    meta: {
      language: row.language,
      wordCount: row.wordCount,
      isAutoGenerated: row.isAutoGenerated,
      fetchedAt: row.fetchedAt,
    },
  }
})
