import { eq } from 'drizzle-orm'
import { useDb } from '../../../utils/db'
import { videoTranscripts } from '../../../db/schema'
import { fetchAndCacheTranscript } from '../../../services/captions-service'

export default defineEventHandler(async (event) => {
  const videoId = getRouterParam(event, 'id')!
  const db = useDb()

  // Force refresh: delete existing then re-fetch
  await db.delete(videoTranscripts).where(eq(videoTranscripts.videoId, videoId))

  const transcript = await fetchAndCacheTranscript(videoId)

  if (!transcript) {
    return { success: false, message: 'No captions available for this video.' }
  }

  const row = await db.query.videoTranscripts.findFirst({
    where: eq(videoTranscripts.videoId, videoId),
  })

  return {
    success: true,
    meta: {
      language: row?.language,
      wordCount: row?.wordCount,
      isAutoGenerated: row?.isAutoGenerated,
      fetchedAt: row?.fetchedAt,
    },
  }
})
